module.exports = pokHandRankings = [
	{
		type: 'High_Card',
		score: 0,
	},
	{
		type: 'Pair',
		score: 1,
	},
	{
		type: 'Tow_Pair',
		score: 2,
	},
	{
		type: ' Three_Of_A_kind',
		score: 3,
	},
	{
		type: 'Straight',
		score: 4,
	},
	{
		type: 'Flush',
		score: 5,
	},
	{
		type: 'Full_House',
		score: 6,
	},
	{
		type: 'Four_Of_A_Kind',
		score: 7,
	},
	{
		type: 'Straight_Flush',
		score: 8,
	},
	{
		type: 'Royal_Flush',
		score: 9,
	},
];

module.exports = cardsNames = [
	{ name: '10C', symbol: 'C', number: 10 },
	{ name: '10D', symbol: 'D', number: 10 },
	{ name: '10H', symbol: 'H', number: 10 },
	{ name: '10S', symbol: 'S', number: 10 },
	{ name: '2C', symbol: 'C', number: 2 },
	{ name: '2D', symbol: 'D', number: 2 },
	{ name: '2H', symbol: 'H', number: 2 },
	{ name: '2S', symbol: 'S', number: 2 },
	{ name: '3C', symbol: 'C', number: 3 },
	{ name: '3D', symbol: 'D', number: 3 },
	{ name: '3H', symbol: 'H', number: 3 },
	{ name: '3S', symbol: 'S', number: 3 },
	{ name: '4C', symbol: 'C', number: 4 },
	{ name: '4D', symbol: 'D', number: 4 },
	{ name: '4H', symbol: 'H', number: 4 },
	{ name: '4S', symbol: 'S', number: 4 },
	{ name: '5C', symbol: 'C', number: 5 },
	{ name: '5D', symbol: 'D', number: 5 },
	{ name: '5H', symbol: 'H', number: 5 },
	{ name: '5S', symbol: 'S', number: 5 },
	{ name: '6C', symbol: 'C', number: 6 },
	{ name: '6D', symbol: 'D', number: 6 },
	{ name: '6H', symbol: 'H', number: 6 },
	{ name: '6S', symbol: 'S', number: 6 },
	{ name: '7C', symbol: 'C', number: 7 },
	{ name: '7D', symbol: 'D', number: 7 },
	{ name: '7H', symbol: 'H', number: 7 },
	{ name: '7S', symbol: 'S', number: 7 },
	{ name: '8C', symbol: 'C', number: 8 },
	{ name: '8D', symbol: 'D', number: 8 },
	{ name: '8H', symbol: 'H', number: 8 },
	{ name: '8S', symbol: 'S', number: 8 },
	{ name: '9C', symbol: 'C', number: 9 },
	{ name: '9D', symbol: 'D', number: 9 },
	{ name: '9H', symbol: 'H', number: 9 },
	{ name: '9S', symbol: 'S', number: 9 },
	{ name: 'AC', symbol: 'C', number: 1 },
	{ name: 'AD', symbol: 'D', number: 1 },
	{ name: 'AH', symbol: 'H', number: 1 },
	{ name: 'AS', symbol: 'S', number: 1 },
	{ name: 'JC', symbol: 'C', number: 11 },
	{ name: 'JD', symbol: 'D', number: 11 },
	{ name: 'JH', symbol: 'H', number: 11 },
	{ name: 'JS', symbol: 'S', number: 11 },
	{ name: 'KC', symbol: 'C', number: 13 },
	{ name: 'KD', symbol: 'D', number: 13 },
	{ name: 'KH', symbol: 'H', number: 13 },
	{ name: 'KS', symbol: 'S', number: 13 },
	{ name: 'QC', symbol: 'C', number: 12 },
	{ name: 'QD', symbol: 'D', number: 12 },
	{ name: 'QH', symbol: 'H', number: 12 },
	{ name: 'QS', symbol: 'S', number: 12 },
];
